spring:
  application:
    name: tosspayments-link
  main:
    lazy-initialization: true # 필요한 빈만 지연 로딩

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: true
  web:
    resources:
      cache:
        period: 0

  datasource:
    url: jdbc:mysql://gateway01.ap-northeast-1.prod.aws.tidbcloud.com:4000/test?sslMode=VERIFY_IDENTITY
    username: 2F6pfXnDpZpM7wr.root
    password: vnynSuOUH2kKnkXs
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        dialect: org.hibernate.dialect.MySQLDialect

widget:
  secret:
    key: "test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6"