spring:
  application:
    name: tosspayments-link

    # application.yml 예시

    devtools:
      livereload:
        enabled: true # 파일 변경 시 브라우저 자동 새로고침 켜기
      restart:
        enabled: true
    thymeleaf: # Thymeleaf 사용 시
      cache: false
    web:
      resources:
        cache:
          period: 0 # 정적 리소스 캐시 끄기

  datasource:
    url: jdbc:mysql://gateway01.ap-northeast-1.prod.aws.tidbcloud.com:4000/test?sslMode=VERIFY_IDENTITY
    username: 2F6pfXnDpZpM7wr.root
    password: vnynSuOUH2kKnkXs
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

widget:
  secret:
    key: "test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6"